/**
 * OpenFood API Swagger documentation
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface Error {
    _body?: string;

    ok?: boolean;

    status?: number;

    statusText?: string;

    type?: number;

    url?: string;
}
