/**
 * OpenFood API Swagger documentation
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Product {
    /**
     * Product ID
     */
    id?: number;

    /**
     * Product objects in OpenFood.
     */
    type?: string;

    attributes?: models.ProductAttributes;

}
